# Generated by Django 5.0.1 on 2024-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('address', models.TextField()),
                ('Domain', models.CharField(choices=[('IT', 'IT'), ('Production', 'Production'), ('Marketing', 'Marketing')], max_length=100)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
