# Generated by Django 5.0.1 on 2024-02-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machines',
            new_name='Machine',
        ),
    ]
